# Generated by Django 5.2.12 on 2026-03-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to='medium/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='media',
            name='webp',
            field=models.ImageField(blank=True, null=True, upload_to='webp/%Y/%m/%d/'),
        ),
    ]
