# Generated by Django 5.2.12 on 2026-03-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_media_medium_media_thumbnail_media_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='clip_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
