# Generated by Django 5.2.12 on 2026-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_media_clip_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
