# Generated by Django 5.2.12 on 2026-03-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_media_latitude_media_location_name_media_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='media',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='media',
            name='longitude',
        ),
        migrations.AddField(
            model_name='media',
            name='external_video_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
