# Generated by Django 5.2.12 on 2026-03-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_media_latitude_remove_media_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='external_video_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='is_video',
        ),
        migrations.RemoveField(
            model_name='media',
            name='video',
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(default='image', upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
