# Generated by Django 5.2.12 on 2026-03-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_media_external_video_id_remove_media_is_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
