# Generated by Django 5.2.12 on 2026-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_media_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.FileField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
